basePath = '/Users/frieda/Downloads/' # TODO '~' should work instead
resultsPath = 'results/'
tempPath = 'temp_'
testPath = 'test_'
lr = 0.4
T = 1
K = 40
F = 5
P = 400
S = 20
n = 50
R = 5
N = n*R
lmbda = 0.05
shapes = [[] for i in range(n)]
shapeEstimates = [[] for i in range(N)]
similarityTransforms = [[] for i in range(N)]
imageAdapters = [[] for i in range(n)]
PRINT_TIME_STATS = True
