basePath = '/Users/frieda/Downloads/'
resultsPath = 'results/'
tempPath = 'temp_'
testPath = 'test_'
lr = 1
T = 1
K = 20
F = 5
P = 400
S = 20
n = 20
R = 4 # Use 1 initialization instead? >:(
N = n*R
lmbda = 0.03
# strongRegressors = [[] for i in range(T)]
# shapeDeltas = [[] for i in range(N)]
# pi = []
shapes = [[] for i in range(n)]
shapeEstimates = [[] for i in range(N)]
# I = [[] for i in range(n)]
# residuals = [[] for i in range(N)]
meanShape = []
meanWidthX = 0
meanHeightX = 0
meanWidthY = 0
meanHeightY = 0
# samplePoints = []
# samplePairs = []
# priorWeights = []
similarityTransforms = [[] for i in range(N)]
imageAdapters = [[] for i in range(n)]
PRINT_TIME_STATS = True
