basePath = '/Users/frieda/Downloads/'
resultsPath = 'results/faceDetector.pkl'
tempPath = 'results/temp_'
testPath = 'results/test_'
lr = 0.1
T = 1
K = 100
F = 5
P = 400
S = 20
n = 5
R = 2 # Use 1 initialization instead? >:(
N = n*R
lmbda = 0.1
strongRegressors = [[] for i in range(T)]
shapeDeltas = [[] for i in range(N)]
pi = []
shapes = [[] for i in range(n)]
shapeEstimates = [[] for i in range(N)]
I = [[] for i in range(n)]
residuals = [[] for i in range(N)]
meanShape = []
meanWidthX = 0
meanHeightX = 0
meanWidthY = 0
meanHeightY = 0
samplePoints = []
samplePairs = []
priorWeights = []
similarityTransforms = []
